development:
  clients:
    default:
      database: twitter_monitoring_dev
      hosts:
        - localhost:27017

# production:
#   host: prod_host
#   port: 1000
#   username: main
#   password: blabla
#   database: cool_demo
